import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:smart_resume_tracker/core/services/hive_service.dart';
import 'package:smart_resume_tracker/features/resume/screens/resume_list_screen.dart';
// import 'firebase_options.dart'; // Will be generated by flutterfire configure

void main() async {
  // 1. Ensure Flutter binding is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase
  // Uncomment and configure with flutterfire cli later.
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );
  // For now, we wrap in try-catch to allow app to run before flutterfire configure
  try {
    await Firebase.initializeApp();
  } catch (e) {
    debugPrint("Firebase initialization failed or not configured: $e");
  }

  // 3. Initialize Hive and open boxes via HiveService
  await HiveService.init();

  // 4. Run the app, wrapped in ProviderScope for Riverpod
  runApp(
    const ProviderScope(
      child: SmartResumeTrackerApp(),
    ),
  );
}

class SmartResumeTrackerApp extends StatelessWidget {
  const SmartResumeTrackerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Smart Resume Tracker',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const ResumeListScreen(),
    );
  }
}
